// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {

    "multi-select": {
      name: "multi-select",
      type: "registry:ui",
      registryDependencies: ["separator","button","badge","popover","command"],
      files: ["registry/ui/multi-select.tsx"],
      component: React.lazy(() => import("@/registry/ui/multi-select.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "multi-select-demo": {
      name: "multi-select-demo",
      type: "registry:example",
      registryDependencies: ["multi-select"],
      files: ["registry/example/multi-select-demo.tsx"],
      component: React.lazy(() => import("@/registry/example/multi-select-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "multi-select-secondary": {
      name: "multi-select-secondary",
      type: "registry:example",
      registryDependencies: ["multi-select"],
      files: ["registry/example/multi-select-secondary.tsx"],
      component: React.lazy(() => import("@/registry/example/multi-select-secondary.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "multi-select-destructive": {
      name: "multi-select-destructive",
      type: "registry:example",
      registryDependencies: ["multi-select"],
      files: ["registry/example/multi-select-destructive.tsx"],
      component: React.lazy(() => import("@/registry/example/multi-select-destructive.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "multi-select-inverted": {
      name: "multi-select-inverted",
      type: "registry:example",
      registryDependencies: ["multi-select"],
      files: ["registry/example/multi-select-inverted.tsx"],
      component: React.lazy(() => import("@/registry/example/multi-select-inverted.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "multi-select-form": {
      name: "multi-select-form",
      type: "registry:example",
      registryDependencies: ["multi-select"],
      files: ["registry/example/multi-select-form.tsx"],
      component: React.lazy(() => import("@/registry/example/multi-select-form.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/hooks/use-mobile.tsx"],
      component: React.lazy(() => import("@/registry/hooks/use-mobile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-toast": {
      name: "use-toast",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/hooks/use-toast.ts"],
      component: React.lazy(() => import("@/registry/hooks/use-toast.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  }